Add `config2` and `getConfig2Address` functions to HuffDeployer.sol
huff-language/foundry-huff pull request #33
Opened 2023-01-27 10:00 UTC by AmadiMichael

Adding `config2(uint256)` and `getConfig2Address(uint256)` lets devs deterministically get and deploy the address where HuffConfig will be deployed to, rather than hardcoding an address.

For example, when trying to fix `TSOwnable.t.sol` in huffmate which was failing it was because of the hardcoded HuffConfig address. I fixed it locally using config2. To make a pull request to huffmate these methods are needed...

Works the same way as config but uses create2 and a salt in uint256 to ease usage

2023-01-27 23:03 UTC, cheethas commented
I think this is a great solution to the `TSOwnable.t.sol` issue, however I've merged a pr https://github.com/huff-language/foundry-huff/pull/31 that i think could solve the same issue in a slightly different way. Do you think we need both?

2023-01-28 09:38 UTC, AmadiMichael commented
> I think this is a great solution to the `TSOwnable.t.sol` issue, however I've merged pr #31 that i think could solve the same issue in a slightly different way. Do you think we need both?

Yeah so i was looking into TSOwnable failing test more and found a rather simple trick to solving the TSOwnable failing test without a need to add config2, by separating the HuffConfig deployment and storing the returned address.

As for config2, we could add it for scenarios where the config address needs to be known before deployment and needs to be deployed later.

2023-01-29 19:29 UTC, devtooligan requested changes
hey hey, thanks so much for your contribution. this looks really cool!

could you please remove the white space changes that probably your linter added?

as you know we are volunteer run and currently quite behind on pr reviews. the additional white space changes here make it a lot harder to see your new diff.

i know we are inconsistent throughout this codebase with the whitespace, if you have an opinion on that or would like to fix some of that, then please submit that in a separate pr.

thanks fren!!

2023-01-29 23:16 UTC, cheethas commented
> As for config2, we could add it for scenarios where the config address needs to be known before deployment and needs to be deployed later.

This sounds like a good approach. As there is pretty sparse documentation for this library in general, shall we change the name to something more verbose and self documenting like `config_with_create_2` and `get_config_with_create_2`. 

With that and the linting fixes mentioned by devtooligan I think this can be merged.

2023-02-02 15:22 UTC, closed without merging

2023-02-23 15:08 UTC, eugenioclrc commented
Hey Guys sorry for reopen this, but its no working for me...
```
address _factory = HuffDeployer.get_config_with_create_2(99);
address factory = HuffDeployer.config_with_create_2(99).deploy("Factory");
assertEq(factory, _factory, "Factory address should be the same");
```

Is `config_with_create_2(salt)` implemented?

2023-02-23 15:21 UTC, AmadiMichael commented
> Hey Guys sorry for reopen this, but its no working for me...
> 
> ```
> address _factory = HuffDeployer.get_config_with_create_2(99);
> address factory = HuffDeployer.config_with_create_2(99).deploy("Factory");
> assertEq(factory, _factory, "Factory address should be the same");
> ```
> 
> Is `config_with_create_2(salt)` implemented?

`get_config_with_create2` and `config_with_create_2` are to deterministically get the address for and deterministically deploy the config contract which in turn you can use to deploy a huff contract, respectively. So in this case, `_factory` returns the address that `HuffConfig` will be deployed to if deployed with salt `bytes32(99)` and `factory` returns the address of `"Factory"` which in this case is deployed by HuffConfig at address created with salt 99


Using normal HuffConfig for deployment would do in this case actually like

```solidity
address factory = HuffDeployer.config().deploy("Factory");
```
Using `config_with_create_2` works too but isn't necessary if there isn't need to know the HuffConfig address before hand

```solidity
address factory = HuffDeployer.config_with_create_2(99).deploy("Factory");
```

But the two addresses above won't be the same as it's two different config addresses that deploys the Factory